apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-consul-register
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-consul-register
    spec:
      containers:
      - name: kube-consul-register
        # image: tczekajlo/kube-consul-register:0.1.4
        image: goodoldjack12/kube-consul-register:dev0.0.3
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1
            memory: 300Mi
        args:
        - -logtostderr=true
        - -configmap=mynamespace/kube-consul-register
        - -watch-namespace=mynamespace
        - -in-cluster=true
  selector:
    matchLabels:
      app: kube-consul-register
